name: "Check GitHub Environments"
description: "Checks if ci, devl, test, and prod environments exist."
inputs:
  github-token:
    description: "GitHub token for authenticating with the GitHub API"
    required: true

branding:
  icon: 'package'
  color: 'blue'

runs:
  using: "node20"
  main: "dist/index.js"