name: Test Check Environments Action

on:
  push:
    branches: [main]

jobs:
  test-check-environments:
    name: Test Check Environments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
